version: "3.8"

services:
  db:
    image: postgres:16
    container_name: facture_devis_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: facture_devis
      POSTGRES_USER: baseuser
      POSTGRES_PASSWORD: password123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
