// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";

import NavBar from "../components/NavBar";
import { AuthProvider } from "./user-auth/infrastructure/services/auth-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <NavBar />
          <Theme appearance="light" accentColor="blue" radius="medium">
            {children}
          </Theme>
          {/* Footer */}
          <footer className="bg-gray-100 text-center py-4 text-sm text-gray-500">
            © {new Date().getFullYear()} - Application Facture & Devis
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
